airtable:
  base:
    # Production Airtable BasedID
    production: "fixme"
    # Testing Airtable BasedID
    test: "fixme"
  # Your Airtable API Key
  apikey: "fixme"
  # Tasks Table - shouldn't need to change this
  tasks: "Tasks"
  # Activity Insight Table - shouldn't need to change this
  activity_insight: "Activity Insight"

unpaywall:
  # This email is sent with request to Unpaywall API
  email: "fixme"

openaccessbutton:
  # API key for open access button: https://openaccessbutton.org/account?next=/api
  key: "fixme"

scholarsphere:
  apikey: "fixme"
  production: "fixme"
  test: "fixme"

rmdb:
 apikey: "fixme"
 production: "fixme"
 test: "fixme"

# Absolute path to directory to search for files (used by deposit)
article_path: "fixme"
